databases:
  - name: infovault
    databaseName: infovault
    user: infovault
    plan: free

services:
  - type: web
    name: infovault
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: infovault
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
      - key: RAILS_ENV
        value: production
